import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Caveat } from 'next/font/google';

const caveat = Caveat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={caveat.className}>{children}</body>
    </html>
  );
}
